SET TIME ZONE '+02:00';

CREATE TABLE IF NOT EXISTS PRICES (
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX idx_prices_brand_start_product_priority
ON PRICES (BRAND_ID, START_DATE, END_DATE, PRODUCT_ID, PRIORITY);